#!/usr/bin/env bash

printusage () {
    echo "Usage: maclock [-l] [-s]"
    echo ""
    echo ""      -x, --xout    : logout"
    echo "       -hi, --hello  : say hello"
    echo "       -s, --sleep   : sleep the display"
    echo "       -l, --lock    : lock the display"
}

LOGOUT=false
SLEEP_COMPUTER=false
LOCK_COMPUTER=false
SAY_HI=false

for i in "$@"
do
    case $i in
        --help|-h)
            printusage
            exit 1
            ;;
        --xout|-x)
           LOGOUT=true
           exit 1
           ;;
        --hello|-hi)
            SAY_HI=true
            exit 1
            ;;
        --sleep|-s)
            SLEEP_COMPUTER=true
            shift
            ;;
        --lock|-l)
	    LOCK_COMPUTER=true
            shift
            ;;
        *)
            printusage
            exit 1
            ;;
    esac
done

# Sleep computer
if [[ $SLEEP_COMPUTER=true ]] ; then

	open -a ScreenSaverEngine

fi

# Lock computer
if [[ $LOCK_COMPUTER = true ]] ; then

    osascript -e 'tell application "System Events"' -e 'log out' -e 'keystroke return' -e end

fi

# Say have a nice day 
if [[ $SAY_HI = true ]] ; then
    say "Hello there";
fi

#Logout
if [[ $LOGOUT = true ]] ; then
osascript <<EOD
        tell application "System Events"
                key code 12 using {control down, command down}
        end tell
EOD
fi

exit 0
